#!/bin/sh

### Config Params ###############################

node="zincBB"

### Setup ######################################

cd `dirname $0`
rm -rf ./wwwroot/nitrogen
ln -s ${PWD}/lib/nitrogen/www ./wwwroot/nitrogen


### Launch #####################################

echo "Starting ZincBB (Standalone)"

exec erl +K true -smp enable                \
-sname ${node}                              \
-pa ${PWD}/lib/*/ebin                       \
-boot start_sasl -s reloader -config sys    \
-eval "application:start(crypto)"           \
-eval "application:start(znbb)"

